preset: symfony

finder:
    exclude:
        - "Resources"
        - "vendor"

enabled:
    - short_array_syntax

disabled:
    - phpdoc_annotation_without_dot # This is still buggy: https://github.com/symfony/symfony/pull/19198
    - single_import_per_statement
