on:
  pull_request: ~
  push:
    branches:
      - "master"

name: Roave
jobs:
  roave_bc_check:
    name: BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            set-safe-directory: '/github/workspace'

      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
